export const TRANSACTION_CATEGORIES = [
  'FOOD_AND_BEVERAGE',
  'TRANSPORTATION',
  'UTILITIES',
  'ENTERTAINMENT',
  'SALARY',
  'INVESTMENT',
  'HEALTHCARE',
  'SHOPPING',
  'OTHER'
] as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const DEFAULT_PAGE_SIZE = 20;
